stages:
  - test
  - setup
  - build_docker

test:
  image: node:20
  script:
    - npm ci --omit=optional
    - npm test

setup:
  rules:
    - if: $CI_COMMIT_TAG
  stage: setup
  image: node:20
  script:
    - npm ci --omit=dev --omit=optional
  artifacts:
    untracked: true
    paths:
      - node_modules/
    expire_in: 5 minutes

docker_build:
  rules:
    - if: $CI_COMMIT_TAG
  stage: build_docker
  dependencies:
    - setup
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    # docker-container drives supports multi-platform builds
    - docker buildx create --driver docker-container --use
    - docker login -u hdegroote -p $DOCKER_PAT
    - docker buildx build --platform linux/amd64,linux/arm64 -t hdegroote/dht-prometheus:latest -t hdegroote/dht-prometheus:$CI_COMMIT_TAG --push .
    - docker logout
