name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  security:
    runs-on: ubuntu-latest
    name: Security
    steps:
      - uses: holepunchto/actions/security-base@v1
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - run: npm run test
      - run: npm run integration
      - run: npm run test:bare
      - run: npm run integration:bare
