name: Integrate
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint
      - run: npm run test
        id: test
        if: '!cancelled()'
      - run: npm run integration
        if: "!cancelled() && steps.test.conclusion == 'success'"
